on: 
  issues:  
    types: [opened]

jobs:
  test_js:
    env: 
      TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
      TRELLO_API_TOKEN: ${{ secrets.TRELLO_API_TOKEN }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: add dependencies
        run: npm install jquery
        run: npm install jsdom
      - name: Add Issue
        uses: ./actions
      
